name: dev
channels:
  - conda-forge
dependencies:
  - python=3.10.8
  - pip=22.3.1
  - pandas=1.5.2
  - plotly=5.11.0
  - python-dotenv=0.21.0
  - psycopg2=2.9.3
  - streamlit=1.16.0
  - sqlalchemy=1.4.45
